#!/usr/bin/env bash

#
# This `themectl` utility writes logs to stderr
# Also prints logs via notify-send (libnotify required)
#
# `--notify-only` flag will waive printing the log to `stderr`.
#
# Usage:
# ```bash
# source $THIS_FILE
# ...
# "$SOME_CMD" || log_error $ID "Something went wrong: $?"
# log_info $ID "Stuff is happening!" --notify-only
# ```
#

###############################################################################
## Configuration ##############################################################
###############################################################################

#
# Default log level (LL)
#
LL_DEFAULT=WARN

#
# Notification daemon backend commands (empty variable for log level = no-op)
#
N_CMDS=(
    "" # ------------------------------- TRACE - #
    "" # ------------------------------- DEBUG - #
    "notify-send --urgency=low" # ------ INFO -- #
    "notify-send --urgency=normal" #---- WARN -- #
    "notify-send --urgency=normal" # --- ERROR - #
    "notify-send --urgency=critical" #-- FATAL - #
)

###############################################################################

# Use these functions
log_trace() { __log "TRACE" "$1" "$2" "$3"; }
log_info()  { __log "INFO"  "$1" "$2" "$3"; }
log_warn()  { __log "WARN"  "$1" "$2" "$3"; }
log_error() { __log "ERROR" "$1" "$2" "$3"; }
log_fatal() { __log "FATAL" "$1" "$2" "$3"; }
log_debug() { __log "DEBUG" "$1" "$2" "$3"; }

# Log Level
LL=$LL_DEFAULT
[ -f "$INCLUDE_DIR/log-level" ] &&
    echo -n "Polling file for log level..." &&
    LL=$(cat "$INCLUDE_DIR/log-level") &&
    echo "set to $LL"

__log_level_value() {
    local OUT="-1"
    case $1 in
        TRACE) OUT=0; ;; DEBUG) OUT=1; ;; INFO) OUT=2 ;;
        WARN) OUT=3; ;; ERROR) OUT=4; ;; FATAL) OUT=5 ;;
    esac
    printf "%b" $OUT
}

__log_filter() {
    [ $(__log_level_value $LEVEL) -ge $(__log_level_value $LL) ] && return 0
    return 1
}

__log() {
    local LEVEL="$1" && shift && ! __log_filter $LEVEL && return 0
    local ID="$1" && shift
    local MSG="$1" && shift
    local SILENT=$([[ "$@" =~ "--silent " ]] && echo 1)
    local N_CMD_IDX=$(__log_level_value "$LEVEL")
    local N_CMD="${N_CMDS[$N_CMD_IDX]}"
    [ ! -z "$N_CMD" ] && ${N_CMD} "$ID:$LEVEL" "$MSG"
    [ -z "$SILENT" ] && echo "$ID:$FUNC:$LEVEL |" "$MSG" >&2
}

