#!/usr/bin/env bash

TC_WOFI="$TC_DIR/wofi"
WOFI_CONFIG_DIR="${WOFI_CONFIG_DIR:-$XDG_CONFIG_HOME/wofi}"

wofi_theme() {
    if [ ! -d "$WOFI_CONFIG_DIR" ]; then
        notify-warn "$FUNCNAME" "Rofi config directory not found. Ignoring."
        return
    fi
    local OUT_DIR="$WOFI_CONFIG_DIR/theme"
    local CSS_TMP="/tmp/theme_woficolors.css"
    local CSS_OUT="$OUT_DIR/colors.css"
    clear_files "$CSS_TMP"
    if [ ! -d "$WOFI_CONFIG_DIR/theme" ]; then
        mkdir "$WOFI_CONFIG_DIR/theme"
    fi
    local COLORS_CSS=
    if [ -f "$COLORS_JSON" ]; then
        colors_to_css "$COLORS_JSON" "$CSS_TMP"
        COLORS_CSS=$(cat "$CSS_TMP" | tr '\n' '|')
        # commit_file "$CSS_TMP" "$CSS_OUT"
    else
		notify-warn "$FUNCNAME" "$COLORS_JSON not found. Ignoring wofi colors."
    fi
    if ! [ -d "$TC_WOFI" ]; then
        notify-warn $FUNCNAME "Wofi config directory missing. Using defaults."
        TC_WOFI="$TC_SKELETON/wofi"
    fi
    for TC_FILE in "$TC_WOFI"/*; do
        local TMP_FILE="/tmp/theme_$(basename $TC_FILE)"
        local OUT_FILE="$OUT_DIR/$(basename $TC_FILE)"
        sed "s/{COLORS_CSS}/${COLORS_CSS}/" "$TC_FILE" | sed "s/|/\n/g" > "$TMP_FILE"
        commit_file "$TMP_FILE" "$OUT_FILE"
    done
}

wofi_clean() {
    clear_dir "$WOFI_CONFIG_DIR/theme/"
    cp -r ${TC_SKELETON}/wofi/* "$WOFI_CONFIG_DIR/theme/"
}

wofi_reload() {
    echo "Nothing to do" > /dev/null
}

