#!/usr/bin/env bash

TC_WOFI="$TC_DIR/wofi"
WOFI_CONFIG_DIR="${WOFI_CONFIG_DIR:-$XDG_CONFIG_HOME/wofi}"

wofi_theme() {
    if [ ! -d "$WOFI_CONFIG_DIR" ]; then
        notify-warn "$FUNCNAME" "Rofi config directory not found. Ignoring."
        return
    fi
    local OUT_DIR="$WOFI_CONFIG_DIR/theme"
    local OUT_COLORS_CSS="$OUT_DIR/colors.css"
    [ ! -d "$OUT_DIR" ] && mkdir -p "$OUT_DIR"
    if [ -f "$COLORS_JSON" ]; then
        colors_to_css "$COLORS_JSON" "$OUT_COLORS_CSS"
    else
		notify-warn "$FUNCNAME" "$COLORS_JSON not found. Ignoring wofi colors."
    fi
    if ! [ -d "$TC_WOFI" ]; then
        notify-warn $FUNCNAME "Wofi config directory missing. Using defaults."
        TC_WOFI="$TC_SKELETON/wofi"
    fi
    for TC_FILE in "$TC_WOFI"/*; do
        local FILE_OUT="$OUT_DIR/$(basename $TC_FILE)"
        echo "$OUT_COLORS_CSS"
        sed 's|{_COLORS_CSS_}|'$OUT_COLORS_CSS'|' "$TC_FILE" >> "$FILE_OUT"
    done
}

wofi_clean() {
    clear_dir "$WOFI_CONFIG_DIR/theme/"
    cp -r ${TC_SKELETON}/wofi/* "$WOFI_CONFIG_DIR/theme/"
}

wofi_reload() {
    echo "Nothing to do" > /dev/null
}

