[colors]
background={{colors.surface.default.hex_stripped}}
foreground={{colors.on_surface.default.hex_stripped}}

selection-foreground={{colors.on_primary.default.hex_stripped}}
selection-background={{colors.primary.default.hex_stripped}}

cursor={{colors.primary.default.hex_stripped}}

# Normal colors
regular0={{colors.surface.default.hex_stripped}}
regular1={{colors.error.default.hex_stripped}}
regular2={{colors.secondary.default.hex_stripped}}
regular3={{colors.primary.default.hex_stripped}}
regular4={{colors.tertiary.default.hex_stripped}}
regular5=d2a6ff
regular6={{colors.tertiary.default.hex_stripped}}
regular7={{colors.on_surface.default.hex_stripped}}

# Bright colors
bright0={{colors.outline_variant.default.hex_stripped}}
bright1=f07178
bright2=c2d94c
bright3=ffb454
bright4=59c2ff
bright5=e6b0ff
bright6=95e6cb
bright7=f0f0f0
