# Default hyprland theme config file.
#
# Hyprland will automatically source this file. Do not rename it.
# You may add files to this directory and source them here.

general {
    col.active_border = rgb(f27852)
    col.inactive_border = rgb(000000)
    border_size = 3
}

