#!/usr/bin/env bash

# Const
MENU_PROMPT="Select a themectl operation."
LFS='
'
OPTS="get\nset\nreload\nclear\ncreate\n"

THEMECTL="$XDG_CONFIG_HOME/scripts/themectl"
THEME_HOME="$XDG_CONFIG_HOME/theme"

TERMINAL="kitty"
EDITOR="nvim"

OPT=$(d_read "$ID" "$OPTS" "$MENU_PROMPT")
[ -z "$OPT" ] && exit 1

case $OPT in
    get)
        notify-send "$ID" "$($THEMECTL get)"
        ;;
    set)
        AV_THEMES="$($THEMECTL ls)"
        THEME_OPT=$(d_read "$ID" "$AV_THEMES" "$MENU_PROMPT")
        if [ -z "$(echo $AV_THEMES | grep ^$THEME_OPT$)" ]; then
            notify-send "$ID" "Theme not found: $THEME_OPT"
        fi
        $("$THEMECTL" set "$THEME_OPT")
        ;;
    reload | clear)
        "$THEMECTL" "$OPT"
        ;;
    create)
        NEW_THEME=$(k_read "$ID" "What would you like to name your new theme?")
        [ -z "$NEW_THEME" ] && notify-send "$ID" "No theme selected." && exit 1
        if "$THEMECTL" create "$NEW_THEME"; then
            "$TERMINAL" "$EDITOR" "$THEME_HOME/$NEW_THEME"
        fi
        exit 1
        ;;
esac
