#!/usr/bin/env bash

THEME=$(cat $THEME_DIR/current-theme)
if [ -f $THEME_DIR/$THEME/fetch-logo.png ]; then
	echo -e "\n" # Workaround for spacing issue
	fastfetch \
		--logo-width 20 --logo-height 9 --logo-type kitty \
		--logo $THEME_DIR/$THEME/fetch-logo.png
else
	fastfetch --logo arch_small
fi

