#!/usr/bin/env bash

set -e
source "$XDG_CONFIG_HOME/scripts/include/menu/util"

# Const
MENU_PROMPT="session [$USER]"
ID="menu-session"

OPTS="\
logout
lock
sleep
shutdown
reboot"

OPT=$(d_read "menu-session" "$OPTS" "$MENU_PROMPT")

case $OPT in
    "logout")
        hyprctl dispatch exit
        ;;
    "lock")
        hyprlock
        ;;
    "sleep")
        systemctl suspend
        ;;
    "shutdown")
        shutdown -ah now
        ;;
    "reboot")
        shutdown -ar now
        ;;
    *)
        exit 1
esac

