#!/usr/bin/env bash

# Get the theme, just in case the shell missed it
THEME="$(cat $THEME_DIR/current_theme)"

# Hyprpaper (set random background per monitor)
WALLPAPER_DIR="$THEME_DIR/$THEME/wallpapers"
MONITORS=$(hyprctl monitors -j | jq -r '.[] | .name')
for MONITOR in $MONITORS; do
	WALLPAPER=$(find "$WALLPAPER_DIR" -type f | shuf -n 1)
	hyprctl hyprpaper reload "$MONITOR","$WALLPAPER" > /dev/null 2>&1
done

# Set Kitty theme and refresh all instances of Kitty
if test -f $THEME_DIR/$THEME/colors; then
	ln -sf $THEME_DIR/$THEME/colors $KITTY_CONFIG_DIRECTORY/current-theme.conf
else
	# Revert to defaults if no theme exists
	rm -f $KITTY_CONFIG_DIRECTORY/current-theme.conf
fi
kill -SIGUSR1 $(pgrep kitty)

