#!/usr/bin/env bash

# const
ROFI_PROMPT="Select an audio sink"

# get list of sinks
SINKS_RAW=$(wpctl status)
SINKS_LN=$(echo "$SINKS_RAW" | grep -n -m 1 "Sinks:" | cut -f1 -d:)
SINKS_LN_END=$((
    $(echo "$SINKS_RAW" | grep -n -m 1 "Sources:" | cut -f1 -d:) -2
))
SINKS_TRIM=$(\
    echo "$SINKS_RAW" | \
    head -n $SINKS_LN_END | \
    tail -n $(($SINKS_LN_END - $SINKS_LN)) \
)
SINKS=""
while IFS= read -r LINE; do
    SINKS="$(echo "$LINE" | cut -c 10- | rev | cut -c 12- | rev)\n${SINKS}"
done <<< "$SINKS_TRIM"

# rofi
OPT=$(echo -e $SINKS | rofi -dmenu -p "$ROFI_PROMPT")

# set new default

NEW_DEFAULT=$(echo $OPT | cut -d "." -f1)
NAME=$(echo $OPT | cut -d "." -f2)
echo $NEW_DEFAULT
if ! wpctl set-default $NEW_DEFAULT; then
    notify-send "rofi-audio" "Could not set default audio sink."
    exit 1
fi

notify-send --urgency=low "rofi-audio" \
    "Set default sink to:\n$(echo $NAME | xargs)"

