#!/bin/bash

# Error if argument is missing
if [ $# -eq 0 ]; then
	echo "No argument supplied."
	exit 1
fi

# A function to ensure the argument is an available theme
available_themes="$(ls -1d $THEME_DIR*/ | sed -e 's/\///')"
check_opt() {
	status=1
	for theme in $available_themes; do
		if [ "$1" = $(basename "$theme") ]; then
			status=0
		fi
	done
	echo $status
}

if [ $(check_opt $1) == 0 ]; then
	echo "$1" > "$THEME_DIR/current_theme"
	export THEME=$1
	echo "Theme changed to: $1"
	# TODO: add a --no-refresh option
	bash -c $HOME/.config/scripts/refreshtheme
	exit 0
else
	echo "Invalid argument"
	echo "Choose from the following themes:" 
	echo "-----------------"
	for theme in $available_themes; do
		echo "$(basename $theme)"
	done
	echo "-----------------"
	exit 1
fi

