#!/usr/bin/env bash

DELAY=${1:-"0"}
POSTDELAY=${2:-"5"}

dunstctl close-all
sleep $DELAY
notify-send --urgency=critical "testdunst" "Message [ Critical ]"
notify-send --urgency=normal   "testdunst" "Message [ Normal   ]"
notify-send --urgency=low      "testdunst" "Message [ Low      ]"
sleep $POSTDELAY
dunstctl close-all

