#!/bin/bash
vol_threshold=140

vol=`$HOME/.config/i3/scripts/get_volume`
inc=$1
if [ -z $vol ] 
then
	vol=0
fi
result=`expr $vol + $inc`

if [ $result -lt 0 ]
then
	result=0	
elif [ $result -gt $vol_threshold ]
then
	result=$vol_threshold
fi 

pactl set-sink-volume 0 $result%
echo "pactl set-sink-volume 0 $result%"
