#!/bin/bash

[ ! mpc > /dev/null 2>&1 ] && echo ""

MAX_LEN=25 # for artist and track names (3 dots inclusive)

IS_PAUSED=

LINE_0=$(mpc | head -n 1 | tail -n 1)
LINE_1=$(mpc | head -n 2 | tail -n 1)
LINE_2=$(mpc | head -n 3 | tail -n 1)

[[ "$LINE_0" =~ Updating\ DB ]] && echo "Updating Database..."
[[ "$LINE_0" =~ volume:.* ]] && echo "--"

get_state_icon() {
    case $1 in
        '[paused]')
            IS_PAUSED=true
            echo ""
            ;;
        *)
            echo ""
            ;;
    esac
}

get_play_time() {
    echo $3
}

truncate() {
    local truncated=$(echo ${1:0:22})
    [ ! "$truncated" == "$1" ] && echo "${truncated}..." || echo "$1"
}

icon=$(get_state_icon $LINE_1)
artist=$(truncate "$(echo "$LINE_0" | cut -d- -f1 | awk '{$1=$1;print}')")
track=$(truncate "$(echo "$LINE_0" | cut -d- -f2 | awk '{$1=$1;print}')")
play_time=$(get_play_time $LINE_1)

echo "${artist:0:MAX_LEN} - ${track:0:MAX_LEN} ${icon} ${play_time}"

