#!/bin/bash

declare -A months
months=( 
  ["01"]="January" 
  ["02"]="February"
  ["03"]="March"
  ["04"]="April"
  ["05"]="May"
  ["06"]="June"
  ["07"]="July"
  ["08"]="August"
  ["09"]="September"
  ["10"]="October"
  ["11"]="November"
  ["12"]="December"
)

declare -A numsuf
numsuf=(
  ["0"]="th"
  ["1"]="st"
  ["2"]="nd"
  ["3"]="rd"
  ["4"]="th"
  ["5"]="th"
  ["6"]="th"
  ["7"]="th"
  ["8"]="th"
  ["9"]="th"
)

raw=`timedatectl | grep Local\ time`
date=`echo $raw | awk '{print $4}' | tr -c '[:digit:]' ' '`
time=`echo $raw | awk '{print $5}' | tr -c '[:digit:]' ' '`

# decompose time
hour=`echo $time | awk '{print $1}'`
minute=`echo $time | awk '{print $2}'`
second=`echo $time | awk '{print $3}'`

hour=`echo ${hour#0}`
isPM=$((hour/12))
hour=$((hour%12))
hour=`printf "%02d" $hour`
if [ $hour = "00" ]; then
	hour="12"
fi
pmString="AM"
if [ $isPM = "1" ]; then
	pmString="PM"
fi

# decompose date
year=`echo $date | awk '{print $1}'`
month=`echo $date | awk '{print $2}'`
day=`echo $date | awk '{print $3}' | sed 's/^0*//g'`

# add day suffix
let dayIndex=${day:(-1)}
suffix=${numsuf[$dayIndex]}
# teens all end with "th"
if [ $day -gt "9" -a $day -lt "20" ]; then
	suffix="th"
fi

echo ${months[$month]} $day$suffix $year " " $hour:$minute:$second $pmString
