#!/bin/bash
HOST='192.168.1.146:2221'
USER='XZ1C'
PASS='EdRulez'
TARGETFOLDER='~/Music'
SOURCEFOLDER='/home/eduardo/Music'

lftp -f "
open $HOST
user $USER $PASS
lcd #SOURCEFOLDER
mirror -p --reverse --delete --verbose $SOURCEFOLDER $TARGETFOLDER
bye
"
